[project]
name = "david-bau-test-task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llama-cpp-python>=0.3.16",
    "torch>=2.8.0",
    "transformers>=4.57.0",
]
